#!/usr/bin/expect

set timeout -1
set host_name [exec cat /etc/hostname]

spawn "./setup_hxe.sh"

expect "HANA_EXPRESS_20]:" { send "\n" }
expect "]:" {send "\n"}
expect "]:" {send "\n"}
expect "]:" {send "\n"}
expect "password:" {send "Pwd$host_name\n"}
expect "password:" {send "Pwd$host_name\n"}
expect "Proceed with installation? (Y/N) :" {send "Y\n"}
#expect "home #" {send "rm -rf /home/*"}

#interact
